import json
from pathlib import Path
from typing import List, Optional
from fastapi import APIRouter, Query

router = APIRouter(
    prefix="/alerts",
    tags=["Alerts"],
)

BASE_DIR = Path(__file__).resolve().parent.parent.parent
ALERT_HISTORY_FILE = BASE_DIR / "alerts" / "alert_history.json"
ZEEK_ALERT_HISTORY_FILE = BASE_DIR / "alerts" / "zeek_alert_history.json"


def _read_alerts_file(path: Path) -> list:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        elif isinstance(data, dict):
            return [data]
        return []
    except Exception:
        return []


@router.get("")
def list_alerts(
    source: str = Query("all", pattern="^(all|standard|zeek)$"),
    limit: int = Query(50, ge=1, le=200)
):
    """
    List historical and active security alerts generated by ARJUN.
    """
    alerts = []
    if source in ("all", "standard"):
        alerts.extend(_read_alerts_file(ALERT_HISTORY_FILE))
    if source in ("all", "zeek"):
        alerts.extend(_read_alerts_file(ZEEK_ALERT_HISTORY_FILE))

    # Sort descending by timestamp if present
    def sort_key(item):
        return item.get("timestamp") or ""

    alerts.sort(key=sort_key, reverse=True)
    return alerts[:limit]
